### ISSUE TITLE
Hanami 0.9.x compatibility

### ISSUE THREAD

**Issue by katafrakt** [katafrakt/hanami-shrine#1]
Latest Hanami release, specifically new model engine, broke hanami-shrine heavily. This was expected, but not to that extent. Right now I have run out of ideas on how to proceed.

**Problem:**

* Entities in Hanami 0.9 are frozen, which means that I cannot set any instance variables. This is done [right after initialization](https://github.com/hanami/model/blob/8775b815edfaef38a1d98cdd83704bbcf2c553f9/lib/hanami/entity.rb#L125).
* Shrine relies on instance variables to cache its `Attacher` class, see [here](https://github.com/janko-m/shrine/blob/master/lib/shrine.rb#L395-L409).
* The attacher is created (usually) on first call of `attachment=`, but new `Hanami::Entity` does not call it on initialization. As a result, I got `can't modify frozen Entity`.

**Solution I can think of:**

Add some kind of `after_initialization` callback before freezing entity. This would allow hanami-shrine (and possibly other gems integrating with hanami-model) to do their job before freezing. I know it sounds a bit Railsy.

-----

I create the issue in this repo because I think this is not exactly Hanami problem, but it may happen that it can only be resolved by Hanami team. Of course, any suggestions on how to approach the problem differently are welcome.

**Comment by janko-m** [comment]
It might be worthwhile to take a look at [shrine-rom-example](https://github.com/janko-m/shrine-rom-example), which includes a [plugin for ROM](https://github.com/janko-m/shrine-rom-example/blob/30ff892216d18ee2b64a1b784a06e489bb3be75d/config/shrine-rom.rb) (which I imagine is similar). However, it currently [requires the model instance to have an `<attachment>_data=` writer](https://github.com/janko-m/shrine-rom-example/blob/30ff892216d18ee2b64a1b784a06e489bb3be75d/config/objects.rb#L14), and I haven't managed to figure out ways around that, which is likely because I don't have the "immutable functional" mindset 😛

Anyway, just putting it out there, as I think whichever ideas come up with hanami-shrine, it could also be ported to shrine-rom (which should at some point be released as a gem), and vice versa.

**Comment by katafrakt** [comment]
@janko-m Thanks for the link! I looked through it, but my problem is more related to the fact that the entity is frozen and does not define setter methods, i.e. you have to pass everything in the constructor and it cannot change. For example, it does not have `attachment_data=` method, which would allow to change image data on promote.

I played around with `prepend` idea suggested by @beauby on Gitter. I was able to get a little further, but because of the issue mentioned about (no setter methods) I got stuck again.

That being said, I'm even closer to be certain that "usual" file upload is now impossible to achieve in Hanami. Which is definitely not good.

@jodosha, perhaps you could help us here a little?

**Comment by beauby** [comment]
@katafrakt Can't you have the method on an other object (say `ImageAttacher` or whatever) and have it call `UserRepository.new.update(...)`?

**Comment by janko-m** [comment]
> but my problem is more related to the fact that the entity is frozen and does not define setter methods, i.e. you have to pass everything in the constructor and it cannot change. For example, it does not have attachment_data= method, which would allow to change image data on promote.

Yes, neither do the dry-rb models that are using in shrine-rom-example; I added the `<attachment>_data` writer method [manually](https://github.com/janko-m/shrine-rom-example/blob/30ff892216d18ee2b64a1b784a06e489bb3be75d/config/objects.rb#L14). That's of course not ideal, but it works.

**Comment by myabc** [comment]
@katafrakt Your plugin could override `Attacher#set`, `#update` and a few other methods:

```ruby
def set(uploaded_file)
  @old = get
  data = convert_to_data(uploaded_file) if uploaded_file
  data = data ? convert_before_write(data) : nil)
  record.class.new(record.to_h.merge(data_attribute => data))
  validate
end
```

(it would actually be better to override `#write` - but I'm not sure if private methods equate to private API here)

```ruby
  def write(value)
    record.class.new(record.to_h.merge(data_attribute => value))
  end
```

**Comment by janko-m** [comment]
@myabc That sounds like a great idea!

And good question – in Shrine private methods don't equate to private API. Actually, there aren't really methods that are part of private API, almost every method from base is used or extended in plugins, so they have enough "weight" that it's very unlikely they will be removed. `Attacher#write` is definitely safe to rely on.

**Comment by jodosha** [comment]
Hi all!

I'm not familiar on how `shrine` work, but is it fine with you to write the value at the initialization time of the entity?

This should be injected by `shrine` in the entity that has the attachment

```ruby
def initialize(attributes = nil)
  # prepare attributes for shrine
  super(attributes)
end
```

or alternatively to have this in native `Hanami::Entity`

```ruby
def update(new_attributes)
  self.class.new(attributes.merge(new_attributes))
end
```

---

Is that attribute part of the database columns or is it a virtual attribute?

For instance, given a `User` entity, backed by a `users` database table. Are you trying to set `avatar` attribute, which corresponds to `users.avatar` in the database? I define this a "_concrete attribute_".

A "_virtual attribute_" is an attribute that is not backed by a corresponding database column. Eg. You try to set `avatar`, but there isn't `users.avatar` column.

I'm asking because entities now **whitelist** the attributes received when initialized. This is done by an [internal schema](http://hanamirb.org/guides/models/entities/#entity-schema). This schema is modeled around the corresponding database table.

If you use _concrete attributes_, you're all set. If you don't (_virtual_), we should work together to add an extension point in `Hanami::Entity`.

**Comment by katafrakt** [comment]
@jodosha Thanks for your comments!

`avatar` and `avatar=` methods are virtual, they wrap calls to `avatar_attacher`, which is an object responsible for persisting, promoting the image etc. The actual database column is `avatar_data`. Note that `avatar_data` is actually not passed as argument to entity constructor. This `avatar_data` is going to be created or updated on save, so it's very different from the idea of having all the data upfront as arguments to entity's constructor.

I like the approach with creating a new entity before save (`self.class.new(attributes.merge(new_attributes))`). But is it safe thing to do? If user or some other library "hacks" the entity and sets some instance variables before freezing, it will be gone after cloning. So it may not be OK to do it like this.

**Comment by nessur** [comment]
upgrading my project to hanami-0.9 this week, I took a 'bad' or 'bull in a china shop' approach:
```
# hanami entities are frozen. This this makes shrine not work.
class Hanami::Entity
  def freeze
    #dont
  end
end
```
and
```
class Image < Hanami::Entity
  include ImageUploader[:image]

  # attributes :name, :model_id, :image_data, :pic_original_url

  def image_data=(image_data)
    @attributes[:image_data] = image_data
  end
end
```
But I would very much like a better solution. I'm guessing/worried that 'disabling' entity freezing might have some downstream effects, other than snubbing dry-rb software design patterns.

**Comment by katafrakt** [comment]
@nessur Thanks for sharing and letting me know that you are using this project! 

I'm still working on a proper solution and I think I'm getting closer and closer to the solution. This will require some changes in the API for sure, but (I hope) won't include any hacks like overwriting `freeze` 😉

**Comment by jodosha** [comment]
Adding @davydovanton and @cllns to this conversation.

**Comment by katafrakt** [comment]
I created a pull request for adding support for Hanami 0.9: see https://github.com/katafrakt/hanami-shrine/pull/2

I know the code is kind of unclear, but I'd appreciate any kind of code review.
