### ISSUE TITLE
Shrine process

### ISSUE THREAD

**Issue by deril** [katafrakt/hanami-shrine#3]
I want to save different versions of image. And I can't understand why using this plugin, all other shrine plugins are not working. I mean using following code `Image.new(file: File.open(...)` does not call process block, which I define in the ImageUploader class. Trying follow the next instruction https://github.com/janko-m/shrine#versions

**Comment by katafrakt** [comment]
Thank you for your report. Some Shrine plugins might not work, because Hanami is vastly different that any other framework Shrine supports. Processing, however, should not be one of them and should work fine. I'll try to look into the issue and will get back to you.

**Comment by janko-m** [comment]
I definitely want to investigate how can I modify Shrine so that this integration can be simpler and that plugins would work. I was following the last PR, but it takes me time to start thinking in this way, because I'm so used to the Active Record pattern with mutable objects.

If we figure out how to make Shrine work well for both patterns, that can then also be ported to dry-rb models which are also immutable. I'll find time soon to dive deeper into this.

**Comment by katafrakt** [comment]
@deril Turns out my latest refactoring fixed the issue with non-working processing. Sorry for inconvenience. Right now the working code is in master, so if you are urged, you can use it. I will release next version soon, but first I want to check out how other default Shrine plugins are working with it.

You can also find a working example with processing here: https://github.com/katafrakt/hanami-shrine-example/tree/processing-support

@janko-m I think this might not be necessary. Turns out I took a wrong turn while finding a fix for Hanami 0.9, which made the implementation cumbersome. But after re-reading your blog posts about Shrine (excellent work, by the way) I found much better solution. You may want to check out this commit: https://github.com/katafrakt/hanami-shrine/commit/72ca173bfc88058d4ab4fb01bcff779723982e1e

**Comment by katafrakt** [comment]
I published version 0.2.1 with working processing. @deril, if you can, please check out if it works for you too.
